services:
  postgres:
    container_name: postgres-sql-books
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_networks
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-boot-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-book_networks
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "8085:1025"

networks:
    spring-boot-network:
        driver: bridge

volumes:
  postgres:
    driver: local