services:
  mongo:
    container_name: mongodb-lms
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-network
    restart: unless-stopped


networks:
  node-network:
    driver: bridge

volumes:
  dbdata: