spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LMS?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb://root:password@localhost:27017/lms?authSource=admin


  jackson:
    serialization:
      fail-on-empty-beans : false

  cache:
    redis:
      time-to-live: 10s

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: id
            clientSecret: secret

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE